import { type Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import NextTopLoader from "nextjs-toploader"
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";
import { SpeedInsights } from "@vercel/speed-insights/next"

const outfit = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Rendrly",
  description: "Generated by gvservices",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${outfit.className} antialiased`}>
          <div className="page-scale-wrapper">
            <NextTopLoader color="#000" />
            {children}
            <Toaster richColors position="bottom-right" />
            <footer className="text-center text-sm text-gray-500 py-4">
              Powered by{" "}
              <a
                href="https://gvservices.netlify.app" // Reemplaza con la URL real si es diferente
                target="_blank"
                rel="noopener noreferrer"
                className="underline"
              >
                GVServices
              </a>
            </footer>
          </div>
          <SpeedInsights />
        </body>
      </html>
    </ClerkProvider>
  );
}
